/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import Monster from "./script/Monster"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1360;
    static height:number=760;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="game.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/Monster.ts",Monster);
    }
}
GameConfig.init();