/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import FlowUI from "./script/FlowUI"
import GameUI from "./script/GameUI"
import Monster from "./script/Monster"
import GameControl from "./script/GameControl"
import Star from "./script/Star"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1360;
    static height:number=760;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="game.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/FlowUI.ts",FlowUI);
        reg("script/GameUI.ts",GameUI);
        reg("script/Monster.ts",Monster);
        reg("script/GameControl.ts",GameControl);
        reg("script/Star.ts",Star);
    }
}
GameConfig.init();